export const cards = [
  { head: "Trade show banners" },
  { head: "Website" },
  { head: "Slide decks" },
  { head: "Mobile apps" },
  { head: "Logos & branding" },
  { head: "Infographics" },
  { head: "Resumes" },
  { head: "Design systems" },
  { head: "Email graphics" },
  { head: "Direct mail" },
  { head: "Direct mail" },
  { head: "Business cards" },
  { head: "Packaging" },
  { head: "Wireframes" },
  { head: "Signage" },
  { head: "SAAS" },
  { head: "Social media graphics" },
  { head: "Blog graphics" },
  { head: "Stationery" },
  { head: "Brand guides" },
  { head: "Pitch decks" },
  { head: "Digital ads" },
  { head: "Billboards" },
  { head: "Icons" },
];
